obj-$(CONFIG_BRCMSTB_NEXUS_API)	+= irq.o
obj-$(CONFIG_BRCMSTB_NEXUS_API)	+= reg.o
obj-$(CONFIG_BRCMSTB_NEXUS_API) += gpio.o

obj-$(CONFIG_BRCMSTB_NEXUS_SPI_API) 		+= spi.o
CFLAGS_spi.o += -I$(src)/../../../../scripts/dtc/libfdt
obj-$(CONFIG_BRCMSTB_NEXUS_CLK_API)	+= clk.o
obj-$(CONFIG_BRCMSTB_NEXUS_DVFS_API)	+= dvfs.o
